### ISSUE TITLE
Parse error when installaing 0.0.2-alpha

### ISSUE THREAD

**Issue by seydu** [henzeb/composer-link#1]
Installing it with 
`composer global require henzeb/composer-link 0.0.2-alpha`
fails with this error message:
```
PHP Parse error:  syntax error, unexpected 'LinkManager' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/vagrant/.composer/vendor/henzeb/composer-link/src/LinkPlugin.php on line 25
```

**Comment by henzeb** [comment]
This is probably because you use a version of php lower than 7.4. I could support that, but I don't see the point, as 7.3 will be security fixes only starting next month, and lower is EOL. For now I've added a minimum constraint.
